[package]
name = "qrlox-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne.workspace = true
qrlox-compiler = { version = "0.1.0", path = "../qrlox-compiler" }
qrlox-macros = { version = "0.1.0", path = "../qrlox-macros" }
qrlox-syntax = { version = "0.1.0", path = "../qrlox-syntax" }

[dev-dependencies]
pretty_assertions = "1.4.1"
indoc = "2.0.6"
